# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(720, 640))
        MainWindow.setMaximumSize(QtCore.QSize(730, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_frame = QtWidgets.QFrame(self.centralwidget)
        self.edit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_frame.setObjectName("edit_frame")
        self.checkBox_p1 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p1.setGeometry(QtCore.QRect(20, 30, 109, 23))
        self.checkBox_p1.setObjectName("checkBox_p1")
        self.checkBox_p2 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p2.setGeometry(QtCore.QRect(20, 60, 109, 23))
        self.checkBox_p2.setObjectName("checkBox_p2")
        self.checkBox_p3 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p3.setGeometry(QtCore.QRect(20, 90, 109, 23))
        self.checkBox_p3.setObjectName("checkBox_p3")
        self.checkBox_p4 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p4.setGeometry(QtCore.QRect(20, 120, 109, 23))
        self.checkBox_p4.setObjectName("checkBox_p4")
        self.file_editor = QtWidgets.QPlainTextEdit(self.edit_frame)
        self.file_editor.setGeometry(QtCore.QRect(340, 30, 351, 251))
        self.file_editor.setPlainText("")
        self.file_editor.setObjectName("file_editor")
        self.checkBox_p5 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p5.setGeometry(QtCore.QRect(20, 150, 109, 23))
        self.checkBox_p5.setObjectName("checkBox_p5")
        self.file_editor_label = QtWidgets.QLabel(self.edit_frame)
        self.file_editor_label.setGeometry(QtCore.QRect(460, 10, 100, 17))
        self.file_editor_label.setObjectName("file_editor_label")
        self.checkBox_p6 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p6.setGeometry(QtCore.QRect(20, 180, 109, 23))
        self.checkBox_p6.setObjectName("checkBox_p6")
        self.checkBox_p7 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p7.setGeometry(QtCore.QRect(20, 210, 109, 23))
        self.checkBox_p7.setObjectName("checkBox_p7")
        self.checkBox_p8 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p8.setGeometry(QtCore.QRect(20, 240, 109, 23))
        self.checkBox_p8.setObjectName("checkBox_p8")
        self.checkBox_p10 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p10.setGeometry(QtCore.QRect(180, 60, 117, 23))
        self.checkBox_p10.setObjectName("checkBox_p10")
        self.checkBox_p15 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p15.setGeometry(QtCore.QRect(180, 210, 117, 23))
        self.checkBox_p15.setObjectName("checkBox_p15")
        self.checkBox_p11 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p11.setGeometry(QtCore.QRect(180, 90, 117, 23))
        self.checkBox_p11.setObjectName("checkBox_p11")
        self.checkBox_p16 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p16.setGeometry(QtCore.QRect(180, 240, 117, 23))
        self.checkBox_p16.setObjectName("checkBox_p16")
        self.checkBox_p14 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p14.setGeometry(QtCore.QRect(180, 180, 117, 23))
        self.checkBox_p14.setObjectName("checkBox_p14")
        self.checkBox_p12 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p12.setGeometry(QtCore.QRect(180, 120, 117, 23))
        self.checkBox_p12.setObjectName("checkBox_p12")
        self.checkBox_p13 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p13.setGeometry(QtCore.QRect(180, 150, 117, 23))
        self.checkBox_p13.setObjectName("checkBox_p13")
        self.checkBox_p9 = QtWidgets.QCheckBox(self.edit_frame)
        self.checkBox_p9.setGeometry(QtCore.QRect(180, 30, 109, 23))
        self.checkBox_p9.setObjectName("checkBox_p9")
        self.verticalLayout.addWidget(self.edit_frame)
        self.preview_frame = QtWidgets.QFrame(self.centralwidget)
        self.preview_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.preview_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.preview_frame.setObjectName("preview_frame")
        self.file_name_input = QtWidgets.QLineEdit(self.preview_frame)
        self.file_name_input.setGeometry(QtCore.QRect(480, 30, 201, 25))
        self.file_name_input.setText("")
        self.file_name_input.setObjectName("file_name_input")
        self.build_button = QtWidgets.QPushButton(self.preview_frame)
        self.build_button.setGeometry(QtCore.QRect(540, 140, 80, 25))
        self.build_button.setObjectName("build_button")
        self.file_preview = QtWidgets.QTextBrowser(self.preview_frame)
        self.file_preview.setGeometry(QtCore.QRect(10, 30, 451, 261))
        self.file_preview.setObjectName("file_preview")
        self.file_preview_label = QtWidgets.QLabel(self.preview_frame)
        self.file_preview_label.setGeometry(QtCore.QRect(190, 10, 83, 17))
        self.file_preview_label.setObjectName("file_preview_label")
        self.reset_button = QtWidgets.QPushButton(self.preview_frame)
        self.reset_button.setGeometry(QtCore.QRect(540, 190, 80, 25))
        self.reset_button.setObjectName("reset_button")
        self.abort_button = QtWidgets.QPushButton(self.preview_frame)
        self.abort_button.setGeometry(QtCore.QRect(540, 240, 80, 25))
        self.abort_button.setObjectName("abort_button")
        self.toolButton = QtWidgets.QToolButton(self.preview_frame)
        self.toolButton.setGeometry(QtCore.QRect(480, 70, 26, 24))
        self.toolButton.setObjectName("toolButton")
        self.text_directory_preview = QtWidgets.QTextBrowser(self.preview_frame)
        self.text_directory_preview.setGeometry(QtCore.QRect(510, 70, 171, 24))
        self.text_directory_preview.setObjectName("text_directory_preview")
        self.line = QtWidgets.QFrame(self.preview_frame)
        self.line.setGeometry(QtCore.QRect(480, 110, 201, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.preview_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI Config Manager"))
        self.checkBox_p1.setText(_translate("MainWindow", "Parameter 1"))
        self.checkBox_p2.setText(_translate("MainWindow", "Parameter 2"))
        self.checkBox_p3.setText(_translate("MainWindow", "Parameter 3"))
        self.checkBox_p4.setText(_translate("MainWindow", "Parameter 4"))
        self.checkBox_p5.setText(_translate("MainWindow", "Parameter 5"))
        self.file_editor_label.setText(_translate("MainWindow", "Append to File"))
        self.checkBox_p6.setText(_translate("MainWindow", "Parameter 6"))
        self.checkBox_p7.setText(_translate("MainWindow", "Parameter 7"))
        self.checkBox_p8.setText(_translate("MainWindow", "Parameter 8"))
        self.checkBox_p10.setText(_translate("MainWindow", "Parameter 10"))
        self.checkBox_p15.setText(_translate("MainWindow", "Parameter 15"))
        self.checkBox_p11.setText(_translate("MainWindow", "Parameter 11"))
        self.checkBox_p16.setText(_translate("MainWindow", "Parameter 16"))
        self.checkBox_p14.setText(_translate("MainWindow", "Parameter 14"))
        self.checkBox_p12.setText(_translate("MainWindow", "Parameter 12"))
        self.checkBox_p13.setText(_translate("MainWindow", "Parameter 13"))
        self.checkBox_p9.setText(_translate("MainWindow", "Parameter 9"))
        self.file_name_input.setPlaceholderText(_translate("MainWindow", "File Name"))
        self.build_button.setText(_translate("MainWindow", "Build File"))
        self.file_preview_label.setText(_translate("MainWindow", "File Preview"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.abort_button.setText(_translate("MainWindow", "Abort"))
        self.toolButton.setText(_translate("MainWindow", "..."))
